const departments=[['経営企画室',2,'投資方針の番人 / 会議進行'],['ファンダ分析部',7,'決算・財務・業界・経営・競合・還元・マクロ'],['テクニカル分析部',3,'長期トレンド / 需給・出来高 / 分割エントリー'],['リスク管理部',5,'サイズ / 集中 / DD / 悪材料 / ショック'],['レッドチーム',3,'空売り目線 / 前提崩し / 失敗パターン'],['情報収集部',4,'決算予定 / 適時開示 / ニュース / 過熱度'],['バックオフィス',3,'日誌 / 四半期レビュー / コンプライアンス']];
const KEY='ai-investment-office-v1';let state=JSON.parse(localStorage.getItem(KEY)||'{"cases":[]}');let currentCaseId=null;
const esc=s=>(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const label=s=>({pending:'要決裁',approved:'採択',hold:'保留',rejected:'却下'})[s]||s;
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function navTo(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navTo(b.dataset.view)));document.getElementById('newAnalysisBtn').onclick=()=>navTo('company');
document.getElementById('departmentGrid').innerHTML=departments.map(d=>`<article class="department-card"><div class="count">${d[1]}</div><h3>${d[0]}</h3><p>${d[2]}</p></article>`).join('');
function reports(c){return[['情報収集部','SOURCE CHECK',['一次情報を優先し、SNSはセンチメントとして分離','決算日・適時開示・関連ニュースを整理']],['ファンダ分析部','RESEARCH',['決算・財務・業界・競合・株主還元を独立評価','未入力の数字を推測で補完しない']],['テクニカル分析部','TIMING ONLY',['月足・週足を中心に長期トレンドを扱う','企業価値の代替指標にはしない']],['リスク管理部','LIMIT FIRST',['ポジションサイズ・集中・想定損失を先に制約','発注権限は持たない']],['レッドチーム','OPPOSE',[`投資仮説「${esc(c.thesis).slice(0,80)||'未記入'}」を前提から疑う`,'空売りするなら何が根拠になるかを列挙']],['バックオフィス','RECORD',['判断理由を同じ書式で残す','3か月後に買った理由が生きているか再確認']]]}
function createCase(){const c={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),createdAt:new Date().toISOString(),ticker:ticker.value.trim(),name:companyName.value.trim(),stage:caseStage.value,horizon:horizon.value,thesis:thesis.value.trim(),evidence:evidence.value.trim(),sourceConfirmed:sourceConfirmed.checked,status:'pending',decisionNote:''};if(!c.ticker&&!c.name){alert('証券コードか会社名を入力してください。');return}c.reports=reports(c);state.cases.unshift(c);currentCaseId=c.id;save();showWorkspace(c);makeMemo(c)}
document.getElementById('createCaseBtn').onclick=createCase;
function showWorkspace(c){caseWorkspace.classList.remove('hidden');workspaceTitle.textContent=`${c.ticker||'—'} ${c.name||'名称未入力'}`;workspaceStatus.textContent=label(c.status);agentReports.innerHTML=c.reports.map(r=>`<article class="report-card"><p class="kicker">${r[1]}</p><h3>${r[0]}</h3><ul>${r[2].map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('');const pass=c.sourceConfirmed&&c.evidence.trim();evidenceGate.innerHTML=pass?'<p><span class="tag">PASS</span> 一次資料が登録されています。AI抽出数字は人間確認前提です。</p>':'<p><span class="tag">ANALYSIS BLOCKED</span> 一次資料が不足しています。AIに数字や事実を推測させないでください。</p>'}
function makeMemo(c){currentCaseId=c.id;const blocked=!(c.sourceConfirmed&&c.evidence.trim());committeeMemo.innerHTML=`<p class="kicker">CEO DECISION PAPER</p><h3>${esc(c.ticker||'—')} ${esc(c.name||'名称未入力')}</h3><p>${blocked?'一次資料不足のため、肯定的な決裁を停止しています。':'一次資料を基準に各部署の論点を統合する決裁書です。'}</p><div class="memo-grid"><div class="memo-box"><h4>Human Thesis</h4><p>${esc(c.thesis||'未記入')}</p></div><div class="memo-box"><h4>Evidence</h4><p>${esc(c.evidence||'未登録')}</p></div><div class="memo-box"><h4>Bull Case</h4><p>成長・財務・還元の支持材料を一次資料から抽出。</p></div><div class="memo-box"><h4>Bear / Red Team</h4><p>前提を最低3点疑い、失敗型との類似を確認。</p></div><div class="memo-box"><h4>Risk Gate</h4><p>上限・集中・DD・ショックを先に確認。</p></div><div class="memo-box"><h4>Data Quality</h4><p>${blocked?'BLOCKED: 一次資料不足':'READY: 原本照合を継続'}</p></div></div><div class="decision-bar"><label>CEO判断メモ<textarea id="decisionNote" rows="3">${esc(c.decisionNote||'')}</textarea></label><div class="decision-buttons"><button class="approve" onclick="decide('approved')" ${blocked?'disabled':''}>採択</button><button class="hold" onclick="decide('hold')">保留</button><button class="reject" onclick="decide('rejected')">却下</button></div></div>`}
window.decide=status=>{const c=state.cases.find(x=>x.id===currentCaseId);if(!c)return;c.status=status;c.decisionNote=document.getElementById('decisionNote').value.trim();c.decidedAt=new Date().toISOString();save();makeMemo(c)};
refreshMemoBtn.onclick=()=>state.cases[0]?makeMemo(state.cases[0]):alert('まだ案件がありません。');
function renderCases(id,limit){const list=limit?state.cases.slice(0,limit):state.cases;document.getElementById(id).innerHTML=list.length?list.map(c=>`<article class="case-card" onclick="openCase('${c.id}')"><div><h3>${esc(c.ticker||'—')} ${esc(c.name||'名称未入力')}</h3><p>${new Date(c.createdAt).toLocaleString('ja-JP')} · ${esc(c.horizon)}</p></div><span class="status ${c.status}">${label(c.status)}</span></article>`).join(''):'<div class="empty">まだ案件がありません。</div>'}
window.openCase=id=>{const c=state.cases.find(x=>x.id===id);if(!c)return;currentCaseId=id;showWorkspace(c);makeMemo(c);navTo('company')};
function renderAll(){const n={pending:0,approved:0,hold:0,rejected:0};state.cases.forEach(c=>n[c.status]++);statPending.textContent=n.pending;statApproved.textContent=n.approved;statHold.textContent=n.hold;statRejected.textContent=n.rejected;renderCases('recentCases',5);renderCases('journalList')}
resetBtn.onclick=()=>{if(confirm('この端末に保存した案件と決裁履歴をすべて削除しますか？')){state={cases:[]};localStorage.removeItem(KEY);renderAll();committeeMemo.innerHTML='<div class="empty">分析案件を作ると、ここに決裁書が生成されます。</div>'}};renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});